/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.tonita.jawbreaker;

import ca.tonita.jawbreaker.panels.EOSPanel;
import ca.tonita.jawbreaker.models.JawBreakerModel;
import ca.tonita.jawbreaker.panels.TOVBuilderPanel;

/**
 *
 * @author atonita
 */
public class JawBreaker extends javax.swing.JFrame {
        private final JawBreakerModel model;

    /**
     * Creates new form JawBreaker
     */
    public JawBreaker() {
        model = new JawBreakerModel();
        initComponents();
        eosPanel.setModel(model);
        tovBuilderPanel.setModel(model);
        tovFamilyPanel.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        eosPanel = new EOSPanel();
        tovBuilderPanel = new TOVBuilderPanel();
        tovFamilyPanel = new ca.tonita.jawbreaker.panels.TOVFamilyPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.addTab("EOS", eosPanel);
        jTabbedPane2.addTab("TOV Builder", tovBuilderPanel);
        jTabbedPane2.addTab("TOV Family", tovFamilyPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("TOV Builder");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the native look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code">
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JawBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JawBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JawBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JawBreaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JawBreaker().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.tonita.jawbreaker.panels.EOSPanel eosPanel;
    private javax.swing.JTabbedPane jTabbedPane2;
    private ca.tonita.jawbreaker.panels.TOVBuilderPanel tovBuilderPanel;
    private ca.tonita.jawbreaker.panels.TOVFamilyPanel tovFamilyPanel;
    // End of variables declaration//GEN-END:variables
}
