/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.tonita.jawbreaker.panels.eos;

import ca.tonita.jawbreaker.equationsOfState.EOSHandler;
import ca.tonita.jawbreaker.equationsOfState.TabulatedHermite;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author atonita
 */
public class NewTableFromFilePanel extends javax.swing.JPanel implements TabulatedEOSGenerator {

    /**
     * Creates new form NewPolyPanel.
     */
    public NewTableFromFilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delimiterGroup = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        filenameTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        useFilenameCheckbox = new javax.swing.JCheckBox();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Filename:");
        jLabel3.setToolTipText("Full path to file.");

        jButton1.setText("Browse");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(null);

        filenameTextArea.setColumns(20);
        filenameTextArea.setLineWrap(true);
        filenameTextArea.setRows(5);
        filenameTextArea.setText("F:\\Projects\\JawBreaker\\data\\eos2.shear.betaEquilibrium.2.t00");
        filenameTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(filenameTextArea);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("EOS name:");
        jLabel4.setToolTipText("Full path to file.");

        nameTextField.setEditable(false);
        nameTextField.setText("Table from file");

        useFilenameCheckbox.setSelected(true);
        useFilenameCheckbox.setText("Use relative filename as EOS name.");
        useFilenameCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useFilenameCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(nameTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useFilenameCheckbox)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)
                            .addComponent(jLabel4))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useFilenameCheckbox)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File chosen = new File(filenameTextArea.getText());
        JFileChooser chooser = new JFileChooser(chosen);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            filenameTextArea.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void useFilenameCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useFilenameCheckboxActionPerformed
        nameTextField.setEditable(!useFilenameCheckbox.isSelected());
    }//GEN-LAST:event_useFilenameCheckboxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup delimiterGroup;
    private javax.swing.JTextArea filenameTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JCheckBox useFilenameCheckbox;
    // End of variables declaration//GEN-END:variables

    public TabulatedHermite getTabulatedEOS() {
        File eosFile = new File(filenameTextArea.getText());
        if (eosFile.exists()) {
            try {
                TabulatedHermite eos = EOSHandler.readTableFromFile(eosFile);
                if (useFilenameCheckbox.isSelected()) {
                    eos.setIdentifier(eosFile.getName());
                } else {
                    eos.setIdentifier(nameTextField.getText());
                }
                return eos;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NewTableFromFilePanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NewTableFromFilePanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Could not read file: " + eosFile.getAbsolutePath(), "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Could not open file: " + eosFile.getAbsolutePath(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
}
